name: lob-gnn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.2.0
      - torch_geometric
      - pandas
      - numpy
      - scikit-learn
      - tqdm
      - pyyaml
